name: 'Chromatic'

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: show pnpm version
        run: pnpm -v
      - name: set pnpm workspace protocol
        run: pnpm config set save-workspace-protocol true

      - name: install dependencies
        run: pnpm install
      - name: build packages
        run: pnpm run workspace-build

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
